"""Canonical task metadata — single source for API, admin, and seeding."""

TASK_DEFINITIONS: list[dict] = [
    {
        "task_type": "email_composer",
        "display_name": "Email Composer",
        "description": "Draft professional emails from rough notes",
        "section": "Everyone",
        "path": "/email-composer",
        "icon": "mail",
        "input_count": 1,
    },
    {
        "task_type": "meeting_mom",
        "display_name": "Meeting to MoM",
        "description": "Turn meeting notes into structured minutes",
        "section": "Everyone",
        "path": "/meeting-mom",
        "icon": "chat",
        "input_count": 1,
    },
    {
        "task_type": "summarise_doc",
        "display_name": "Summarise Document",
        "description": "Extract key takeaways from long documents",
        "section": "Everyone",
        "path": "/summarise-doc",
        "icon": "document",
        "input_count": 1,
    },
    {
        "task_type": "tone_fixer",
        "display_name": "Tone Fixer",
        "description": "Rewrite text for a different professional tone",
        "section": "Everyone",
        "path": "/tone-fixer",
        "icon": "sparkles",
        "input_count": 1,
    },
    {
        "task_type": "translate",
        "display_name": "Translate",
        "description": "Translate to English, Hindi, or Gujarati",
        "section": "Everyone",
        "path": "/translate",
        "icon": "language",
        "input_count": 1,
    },
    {
        "task_type": "status_report",
        "display_name": "Status Report",
        "description": "Generate formal weekly project status reports",
        "section": "Delivery / PM",
        "path": "/status-report",
        "icon": "chart",
        "input_count": 1,
    },
    {
        "task_type": "risk_register",
        "display_name": "Risk Register",
        "description": "Identify and document project risks formally",
        "section": "Delivery / PM",
        "path": "/risk-register",
        "icon": "shield",
        "input_count": 1,
    },
    {
        "task_type": "explain_code",
        "display_name": "Explain Code",
        "description": "Understand code snippets in plain language",
        "section": "Developers",
        "path": "/explain-code",
        "icon": "code",
        "input_count": 1,
    },
    {
        "task_type": "commit_message",
        "display_name": "Commit Message",
        "description": "Write clear, conventional Git commit messages",
        "section": "Developers",
        "path": "/commit-message",
        "icon": "commit",
        "input_count": 1,
    },
    {
        "task_type": "bug_report",
        "display_name": "Bug Report",
        "description": "Structure bug reports with all required detail",
        "section": "Developers",
        "path": "/bug-report",
        "icon": "bug",
        "input_count": 1,
    },
    {
        "task_type": "eligibility_check",
        "display_name": "Eligibility Check",
        "description": "Assess RFP or tender eligibility quickly",
        "section": "BD / Presales",
        "path": "/eligibility-check",
        "icon": "check",
        "input_count": 2,
    },
    {
        "task_type": "de_ai_text",
        "display_name": "De-AI Text",
        "description": "Make AI-generated text sound more human",
        "section": "BD / Presales",
        "path": "/de-ai-text",
        "icon": "wand",
        "input_count": 1,
    },
]

TASK_DEFINITION_BY_TYPE = {t["task_type"]: t for t in TASK_DEFINITIONS}
